version: "3.4"

networks:
  localnet:
    driver: bridge

services:

  postgres:
    image: postgres:14.2
    container_name: usmartpro-pg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=social
    volumes:
      - ../../postgres/data:/var/lib/postgresql/data
      - ../migrations/initdb:/docker-entrypoint-initdb.d
    networks:
      - localnet

  migrations:
    container_name: usmartpro-migrations
    build:
      context: .
      dockerfile: ./build/migrations/Dockerfile
    depends_on:
      - postgres
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgresql://postgres:postgres@postgres:5432/social?sslmode=disable"
    command: [ "/bin/sh", "-c", "net-wait-go -addrs postgres:5432 && sleep 5 && /bin/goose up" ]

  social:
    container_name: usmartpro-app
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    restart: always
    depends_on:
      - postgres
      #- rabbit
    ports:
      - 8000:8000
    environment:
            LOG_LEVEL: ${LOG_LEVEL}
            LOG_FILENAME: ${LOG_FILENAME}
            STORAGE_TYPE: ${STORAGE_TYPE}
            STORAGE_DSN: ${STORAGE_DSN}
            HTTP_HOST: ${HTTP_HOST}
            HTTP_PORT: ${HTTP_PORT}
            RABBIT_DSN: ${RABBIT_DSN}
            RABBIT_EXCHANGE: ${RABBIT_EXCHANGE}
            RABBIT_QUEUE: ${RABBIT_QUEUE}
    networks:
      - localnet

  tests:
    container_name: usmartpro-tests
    build:
      context: .
      dockerfile: ./build/tests/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../logs/tests:/var/logs
    networks:
      - localnet
